name: Echo Toolkit CI

on:
  push:
    paths:
      - 'Echo-Community-Toolkit/**'
      - 'scripts/ci/run_toolkit_ci.sh'
      - '.github/workflows/echo-toolkit-ci.yml'
  pull_request:
    paths:
      - 'Echo-Community-Toolkit/**'
      - 'scripts/ci/run_toolkit_ci.sh'
      - '.github/workflows/echo-toolkit-ci.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run Echo Toolkit suite
        run: bash scripts/ci/run_toolkit_ci.sh
