name: Kira Prime CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'kira-prime/**'
      - '.github/workflows/kira-prime-ci.yml'
  pull_request:
    paths:
      - 'kira-prime/**'
      - '.github/workflows/kira-prime-ci.yml'
  workflow_dispatch:

jobs:
  prime:
    runs-on: ubuntu-latest
    env:
      CI_SKIP_SBERT: '1'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: kira-prime
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

      - name: Run pytest suite
        working-directory: kira-prime
        run: python -m pytest -q
