name: VesselOS Dev Research CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'vesselos-dev-research/**'
      - '.github/workflows/vesselos-research-ci.yml'
  pull_request:
    paths:
      - 'vesselos-dev-research/**'
      - '.github/workflows/vesselos-research-ci.yml'
  workflow_dispatch:

jobs:
  research:
    runs-on: ubuntu-latest
    env:
      CI_SKIP_SBERT: '1'
      COLLAB_SMOKE_ENABLED: '0'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: vesselos-dev-research
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi

      - name: Run pytest suite
        working-directory: vesselos-dev-research
        run: python -m pytest -q
